language: python
python: 3.6
# install requirements
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
deploy:
  provider: heroku
  api_key:
    secure: "223c9a64-0aa7-48f0-a581-a836d2d2b15d"
  app: still-brook-93827